### ISSUE TITLE
Generating a new component fails on a Window 10 machine

### ISSUE THREAD

**Issue by andy-gutsche** [Veams/cli#1]
**Steps to reproduce:**
Scaffolding new component with `veams -g c testcomponent`. Answer Questions.

**Expected Result:**
Component can be scaffolded by answering all questions

**Actual result:**
Scaffolding fails after answering the _WrapWith_ question with a "Trying to copy from a source that does not exist" error

**Hint:**
On MacOS machines everything works as expected

**Comment by natrenakres** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\@veams\generator-veams\generators\blueprint\templates/componentC:/Users/Anwender/AppData/Roaming/nvm/v8.11.1/node_modules/@veams/cli/node_modules/@veams/generator-veams/generators/blueprint/templates/component/data/bp.json.ejs
    at EditionInterface.exports.copy (C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\mem-fs-editor\lib\actions\copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)
    at module.exports.scaffold (C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\@veams\generator-veams\mini-generators\blueprints\scaffold.js:22:13)
    at module.exports.scaffold (C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\@veams\generator-veams\generators\blueprint\index.js:71:21)
    at Object.<anonymous> (C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\yeoman-generator\lib\index.js:417:23)
    at C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\run-async\index.js:24:19
    at C:\Users\Anwender\AppData\Roaming\nvm\v8.11.1\node_modules\@veams\cli\node_modules\yeoman-generator\lib\index.js:418:9
    at runCallback (timers.js:794:20)

**Computer: Windows 10
nodejs: v8.11.1
@veams/generator-veams: 1.0.0-rc5
@veams/cli: 1.0.0-rc2
inserter: 1.1.2**

**Comment by Sebastian-Fitzner** [comment]
Will take a look over the weekend ... Thx for the hint.

**Comment by Sebastian-Fitzner** [comment]
After some invest, I fixed the bug on windows. Tested it on my own windows machine 10 pro ...
